### PR TITLE
chained Var.combine: Add failing test case

### PR DESCRIPTION
**Pull request by fdietze**

### CODE REVIEW

**Comment by cornerman** [comment]
@fdietze Test is working. What did we want to test? :)

**Comment by fdietze** [comment]
It was about the Rx block not behaving the same as an implementation without.

**Comment by cornerman** [comment]
So, it works now as expected? Should we just merge?

**Comment by fdietze** [comment]
I'm not sure, this test case is adding any value, because it's not testing for anything specific. I'm fine if we just close it.

**Pull request closed without merging**
